In [6]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
x=np.array([[1,2,3],[2,3,4]])

In [15]:
x-np.mean(x,axis=0)

array([[-0.5, -0.5, -0.5],
       [ 0.5,  0.5,  0.5]])

In [21]:
np.ones((x.shape[0],x.shape[1]))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
x[1,:]

array([2, 3, 4])